function ptchMtrx = images2Mtrx (image, rfSize)
%%% generate all patches within an image with mutiple maps;
%%% and then output each patch in vectors; 
%%% all patches are listed in matrix ptchMtrx where rows are ordered along 
%%% the order generated by im2col
dimImage = size(image);
if length(dimImage) == 4
    image = reshape(image, dimImage(2), dimImage(3), dimImage(4));
end

numImgRow = dimImage(2);
numImgCol = dimImage(3);
numMaps = dimImage(4);

% numImgRow = Img_DIM(1);
% numImgCol = Img_DIM(2);
    
numBlkRow = numImgRow-rfSize+1;
numBlkCol = numImgCol-rfSize+1;
rwpatches = zeros(rfSize*rfSize, numBlkCol*numBlkRow,numMaps);
image = reshape(image, numImgRow,numImgCol,numMaps);
parfor kk = 1:numMaps
    Xtemp = reshape(image(:,:,kk),numImgRow,numImgCol);
    rwpatches(:,:,kk) = im2col(Xtemp,[rfSize, rfSize]);
end
clear Xtemp
ptchMtrx = zeros(numBlkCol*numBlkRow, rfSize*rfSize*numMaps);
parfor jj = 1:numBlkCol*numBlkRow
    buffer = rwpatches(:,jj,:);
    ptchMtrx(jj,:) = buffer(:)';
end

end